// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiB4V071e74AnQwM4SQoaAMruTx7tNtCQ',
    appId: '1:659826555404:web:c0f924f55650e9b9f54c29',
    messagingSenderId: '659826555404',
    projectId: 'deliveryapp-86dc9',
    authDomain: 'deliveryapp-86dc9.firebaseapp.com',
    storageBucket: 'deliveryapp-86dc9.appspot.com',
    measurementId: 'G-6JYCEPGVEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcTiWGn5PbnvIkogjIvoc5xa3BOlJe_DM',
    appId: '1:659826555404:android:cbc53b612ab7c0b6f54c29',
    messagingSenderId: '659826555404',
    projectId: 'deliveryapp-86dc9',
    storageBucket: 'deliveryapp-86dc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3ZXcByl5sma7vqcSMzxz2RcVV_NyL7d4',
    appId: '1:659826555404:ios:c71ac7ce947b8d96f54c29',
    messagingSenderId: '659826555404',
    projectId: 'deliveryapp-86dc9',
    storageBucket: 'deliveryapp-86dc9.appspot.com',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3ZXcByl5sma7vqcSMzxz2RcVV_NyL7d4',
    appId: '1:659826555404:ios:0cb192ad37cc4bd1f54c29',
    messagingSenderId: '659826555404',
    projectId: 'deliveryapp-86dc9',
    storageBucket: 'deliveryapp-86dc9.appspot.com',
    iosBundleId: 'com.example.deliveryApp.RunnerTests',
  );
}
